apiVersion: v1
kind: ConfigMap
metadata:
  namespace: seiscomp
  name: seiscomp-config
  labels:
    app: seiscomp
data:
  SEISCOMP_ROOT: /opt/seiscomp
  DB_HOST: seiscomp-mariadb-svc
  SEISCOMP_DB: seiscomp
  scmaster.cfg.orig: |
    core.plugins = dbmysql
    queues.production.plugins = dbstore
    queues.production.processors.messages = dbstore
    queues.production.processors.messages.dbstore.driver = mysql
    queues.production.processors.messages.dbstore.read = sysop:sysop@db/seiscomp
    queues.production.processors.messages.dbstore.write = sysop:sysop@db/seiscomp
  global.cfg: |
    datacenterID = ""
    agencyID = ""
    organization = ""
    core.plugins = dbmysql
  kernel.cfg: ""
  SEISCOMP_SAMPLES_M: "60"