apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dataprovider
  name: seiscomp-fdsnws
  labels:
    app: seiscomp
spec:
  selector:
    matchLabels:
      app: seiscomp
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: seiscomp
        tier: frontend
    spec:
      securityContext:
        fsGroup: 1000
      imagePullSecrets:
        - name: regcred
      containers:
        - name: seiscomp-fdsnws
          image: cnthub.ct.int.ingv.it/dataprovider/seiscomp-5.3.0:0.8
          imagePullPolicy: IfNotPresent
          env:
            - name: SEISCOMP_ROOT
              valueFrom:
                configMapKeyRef:
                  name: seiscomp-config
                  key: SEISCOMP_ROOT
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: seiscomp-config
                  key: DB_HOST
            - name: SEISCOMP_DB
              valueFrom:
                configMapKeyRef:
                  name: seiscomp-config
                  key: SEISCOMP_DB
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: seiscomp-secret
                  key: MARIADB_ROOT_PASSWORD
            - name: SEISCOMP_USER
              valueFrom:
                secretKeyRef:
                  name: seiscomp-secret
                  key: SEISCOMP_USER
            - name: SEISCOMP_USER_PWD
              valueFrom:
                secretKeyRef:
                  name: seiscomp-secret
                  key: SEISCOMP_USER_PWD
            - name: SEISCOMP_SAMPLES_M
              valueFrom:
                configMapKeyRef:
                  name: seiscomp-config
                  key: SEISCOMP_SAMPLES_M
            - name: SEISCOMP_FDSNWS_LOG_PATH
              valueFrom:
                configMapKeyRef:
                  name: seiscomp-config
                  key: SEISCOMP_FDSNWS_LOG_PATH
          volumeMounts:
            - name: config
              mountPath: /opt/seiscomp/etc/global.cfg
              subPath: global.cfg
            - name: config
              mountPath: /opt/seiscomp/etc/kernel.cfg
              subPath: kernel.cfg
            - name: config
              mountPath: /opt/seiscomp/etc/scmaster.cfg.orig
              subPath: scmaster.cfg.orig
            - name: nfs-vol
              mountPath: /nfs_data
          livenessProbe:
            exec:
              command:
                [
                  "/bin/bash",
                  "-c",
                  "wget http://localhost:8080 -O /dev/null",
                ]
            initialDelaySeconds: 20
            periodSeconds: 5
          readinessProbe:
            exec:
              command:
                [
                  "/bin/bash",
                  "-c",
                  "wget http://localhost:8080 -O /dev/null",
                ]
            initialDelaySeconds: 15
            timeoutSeconds: 5
          startupProbe:
            httpGet:
              path: http://localhost:8080
              port: service-port
            failureThreshold: 30
            periodSeconds: 10
          resources:
            requests:
                memory: "2Gi"
                cpu: "500m"
            limits:
                memory: "4Gi"
                cpu: "1000m"
          ports:
            - containerPort: 8080
              name: service-port
          securityContext:
            runAsUser: 1000
            runAsGroup: 1001
      volumes:
        - name: config
          configMap:
            name: seiscomp-config
        - name: nfs-vol
          nfs:
            server: hpcfdsn1.ct.int.ingv.it
            path: /home/fdsnmanager/hpcfdsn1SDS
