apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seiscomp-mariadb
  labels:
    app: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  serviceName: seiscomp-mariadb-svc
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      securityContext:
        fsGroup: 1001
      containers:
        - name: mariadb
          image: mariadb:11.8.3
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: seiscomp-db-secret
          livenessProbe:
            exec:
              command:
                [
                  "healthcheck.sh", "--connect", "--innodb_initialized"
                ]
            initialDelaySeconds: 20
            periodSeconds: 5
          readinessProbe:
            exec:
              command:
                [
                  "healthcheck.sh", "--connect", "--innodb_initialized"
                ]
            initialDelaySeconds: 15
            timeoutSeconds: 5
          ports:
            - containerPort: 3306
              name: mariadb
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
              subPath: mysql-data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
