apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# namePrefix: staging-

namespace: seiscomp-staging

commonLabels:
  app: seiscomp-mariadb

patches:
  - path: statefulset-patch.yaml
    target:
      kind: StatefulSet
      name: seiscomp-mariadb

# Eg: to change the image tag in production
# images:
# - name: ghcr.io/<production_image>
#   newTag: v1.4.0-stable

generatorOptions:
  labels:
    app: seiscomp-mariadb
  disableNameSuffixHash: true

secretGenerator:
- name: seiscomp-db-secret
  behavior: replace
  envs:
  - .env.secret
  