apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seiscomp-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: dataprovider-strip-seiscomp-prefix@kubernetescrd
spec:
  rules:
    - host: dataprovider.ct.int.ingv.it
      http:
        paths:
          - path: /seiscomp
            pathType: Prefix
            backend:
              service:
                name: seiscomp-svc
                port:
                  number: 8080
