apiVersion: apps/v1
kind: Deployment
metadata:
  name: seiscomp-fdsnws-deployment
  labels:
    app: seiscomp
spec:
  template:
    spec:
      containers:
        - name: seiscomp-fdsnws
          image: <staging_repo_url>/<staging_project>/seiscomp-5.3.0:0.8
          resources:
            requests:
                memory: "1Gi"
                cpu: "250m"
            limits:
                memory: "2Gi"
                cpu: "500m"
      volumes:
        - name: nfs-vol
          nfs:
            server: hpcfdsn1.<local_staging>.it
            path: /home/fdsnmanager/hpcfdsn1SDS