apiVersion: v1
kind: ConfigMap
metadata:
  name: seiscomp-config
  labels:
    app: seiscomp
data:
  scmaster.cfg.orig: |
    core.plugins = dbmysql
    queues.production.plugins = dbstore
    queues.production.processors.messages = dbstore
    queues.production.processors.messages.dbstore.driver = mysql
    queues.production.processors.messages.dbstore.read = sysop:sysop@db/seiscomp
    queues.production.processors.messages.dbstore.write = sysop:sysop@db/seiscomp
  global.cfg: |
    datacenterID = ""
    agencyID = ""
    organization = ""
    core.plugins = dbmysql
  kernel.cfg: ""
